model_params:
  name: 'DFCVAE'
  in_channels: 3
  latent_dim: 128

data_params:
  data_path: "Images/"
  csv_file_train: "Train.csv"
  csv_file_valid: "Valid.csv"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 1.0
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 1500

logging_params:
  save_dir: "logs/"
  name: "DFCVAE"
